### PR TITLE
Test indexer utils

### PR DESCRIPTION
**Pull request by carlosvdr**
Added more unit tests to this file

### CODE REVIEW

**Comment by aasseman** [comment]
Why not check the value of `res` instead of just `assert res`?

**Comment by carlosvdr** [comment]
thought wouldnt be necesarry since I mocked the response just before, but if you believe its best sure I can add it also and assert the values of the response

**Comment by aasseman** [comment]
Ok, had to refresh my memory of the code being tested. Indeed it doesn't make sense to test the values since they come directly from the mock return value. The problem though is that there is nothing to test here, I think.

**Comment by carlosvdr** [comment]
Yeah in that you are right, its not like we can exactly test the call, but its more like testing the logic and the flow does follow what we expect it to do.
Its pretty straight forward in this test tho, since everything is from an external source as you say

**Pull request closed without merging**
