### PR TITLE
Refactor autoagora

### PR DESCRIPTION
**Pull request by carlosvdr**

### CODE REVIEW

**Review by aasseman — CHANGES_REQUESTED** [review]
Looks good.
However this test:
https://github.com/semiotic-ai/autoagora/blob/cd2cd0065218585d023d66ffa17df1a17cf3643e/tests/test_model_builder.py#L31-L58
Does not check that the 2 Agora entries get added correctly, but only checks that the version header is correct.

**Comment by aasseman** [comment]
Successful test in prod

**Comment by carlosvdr** [comment]
Regarding the comment I just added extra assertion where it checks if inside the model the queries can be found, since in other tests. Could make a literal check if the whole model looks good but I think it would be too much. Since it would be having there all the model ina variable, if you consider its better then sure could add it in the constant file for tests

**Review by aasseman — DISMISSED** [review]
:shipit:

**Review by aasseman — APPROVED** [review]
:shipit:

**Pull request merged**
